description: "Hello, thanks for visiting my website. Use the navigation bars or links below to find out more about me. I am communication engineer 
and PhD researcher in Electrical and Electronic Engineering at the University of Glasgow, with a focus on wireless communication. 
My research looks at how to network the internet-of-things (IoT) for underwater applications. 
My core competencies are in wireless communication (including 5G and beyond 5G) and IoT networking. 
I have strong cultural and emotional intelligence which I have used in numerous leadership
positions and has enabled me to work well with other people."
email: "kenechi.omeke@glasgow.ac.uk"
twitter: "https://twitter.com/kenechi_omeke"
linkedin: "https://www.linkedin.com/in/kenomeke"
