title: Dr Kenechi Omeke
description: AI Engineer & Climate Researcher
url: "https://kenechiomeke.github.io"
author: Kenechi Omeke

# Theme settings
theme: minima 
header_pages:
  - experience.md
  - research.md
  - publications.md
  - community.md
  - skills.md

exclude_title_from_nav: true

# Social links
github_username: kenechiomeke
linkedin_username: Kenechi Omeke
google_scholar: AVQJbh4AAAAJ

# Additional settings
show_excerpts: true

collections:
  projects:
    output: true
  publications:
    output: true
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap