# Create _config.yml
title: Dr Kenechi Omeke
description: AI Engineer & Climate Researcher
url: "https://kenechiomeke.github.io"
author: Ken Omeke
theme: minima  # or choose another theme

# Social links
github_username: kenechiomeke
linkedin_username: Kenechi Omeke
google_scholar: AVQJbh4AAAAJ

# Additional settings
show_excerpts: true