description: "Hello, thanks for visiting my website. Use the navigation bars or links below to find out more about me."
email: "kenechi.omeke@glasgow.ac.uk"
twitter: "https://twitter.com/kenechi_omeke"
